spring:
  datasource:
    url: jdbc:mysql://kccinterns.cf6uagika0sw.ap-northeast-2.rds.amazonaws.com:3306/happy_desk?serverTimezone=Asia/Seoul
    username: admin
    password: birdsilver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: false
    show-sql: true